version: '3'
services:
  ai_backend:
    build:
      context: .
      dockerfile: Dockerfile.ai
    ports:
      - "5001:5001"

  ui_backend:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "5000:5000"
    depends_on:
      - ai_backend
